spring:
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:social;DB_CLOSE_ON_EXIT=FALSE
    username: admin
    password:
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true

server:
  port: 8080

security:
  application:
    key: 123456

management:
  endpoint:
    logfile:
      external-file: logs/social-service.log
